# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: google/dart:latest
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: mkdir build_tmp
      - run: dart compile exe bin/main.dart -o ./build_tmp/weather_report-$(uname)-$(uname -m).exe
      - store_artifacts:
          path: ./build_tmp/




workflows:
  build:
    jobs:
      - build-medium