# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https
          sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          
          # Update again and install
          sudo apt update
          sudo apt install dart

          # Set PATH in profile for downstream commands
          echo "export PATH=$PATH:/usr/lib/dart/bin" >> $BASH_ENV
          
      - run: mkdir build_tmp
      - run: dart compile exe bin/main.dart -o ./build_tmp/weather_report-$(uname)-$(uname -m).exe
      - store_artifacts:
          path: ./build_tmp/




workflows:
  build:
    jobs:
      - build-medium