name: create diagram using GitHub repo-visualizer

on:
    push:
      branches: [ main ]
      paths:
        - 'bin/**'
        - 'test/**'
        - 'lib/**'
        - 'pubspec.yaml'
        - 'pubspec.lock'
        - '.github/workflows/create-diagram.yml'
    pull_request:
      branches: [ main ]

jobs:
    create-diagram:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Update diagram using Repo Visualizer
              uses: githubocto/repo-visualizer@0.8.2
              with:
                output_file: "output-diagram.svg"
                artifact_name: "my-diagram"
            - name: Get artifact
              uses: actions/download-artifact@v2
              with:
                name: "my-diagram"
                path: "downloads"
